[package]
name = "xray_core"
version = "0.1.0"
authors = ["Nathan Sobo <nathan@github.com>"]

[dependencies]
rand = "0.3"
futures = "0.1"

[dev-dependencies]
futures-cpupool = "0.1"
tokio-core = "0.1"
