language: rust

rust:
- nightly

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
- rustup target add wasm32-unknown-unknown
- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
- nvm install v8.9.3
- wasm-bindgen -V || cargo install wasm-bindgen-cli

# Create a virtual display for electron
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

script: script/cibuild

cache:
  cargo: true
  yarn: true

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: change
