language: rust

rust:
- stable

before_install:
- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
- nvm install v8.9.3

# Create a virtual display for electron
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

script:
- script/build
- script/test

cache:
  cargo: true
  directories:
  - xray_electron/node_modules

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: change
