language: rust

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
- nvm install v11

# Create a virtual display for electron
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

script: script/cibuild

cache:
  cargo: true
  yarn: true

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: change
