[package]
name = "napi"
version = "0.1.0"
authors = ["Nathan Sobo <nathan@github.com>"]

[features]
node8 = []
node9 = []

[dependencies]
futures = "0.1.17"

[build-dependencies]
bindgen = "0.32.1"
cc = "1.0"
glob = "0.2.11"

[workspace]
exclude = ["test_module"]
